version: "3.9"
services:
  app:
    env_file:
      - .env
    container_name: coffee_house_server
    # restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - "$PORT:$PORT"

    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine3.17
    container_name: postgres_coffee_house
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - postgres_coffee_house:/data/postgres
    env_file:
      - .env


volumes:
  postgres_coffee_house:
    driver: local
networks:
  default:
    driver: bridge    
